sudo: false
dist: trusty
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
install:
  - npm install
script: npm run lint && npm run build && npm test
before_deploy: npm run build
deploy:
  provider: npm
  email: development@platforme.com
  skip_cleanup: true
  api_key:
    secure: R/Mw1/u38ENkBfpmWf7No8wKPxduNWVDKRXGlgKU4pYk8YefmRvH8S3zjLTP5vwbvpFwotl6gKJmm5TSW8OLp3LHm6AQWxbIxNiWSJSgfgYMrlM58BIUzYuDKFcU0gmxfCXhpiv88RAfHMCQ1FyHbrv6zjdUVgSu0UMapSEUJU7nTUbLz7ejxY9zxCBzUUBB48JKY7Dk1cfxfBjwf+z+lMygCgg9nk4bQZCGsHiIxQrh07t8O9D/N559r4cL/CFd7nVBW4kTk1iZ2Izt41fYR4fazlmT51QVbzxf10EyeWs31vi0jbC8rMI27hPSLdYPZWRxCHTJrQ1dzBfK/zto/237ksOUFXbRVPPADrSn1StR+4zu2u6yskoS8l1E+UFxmR5044iBZQktuxZe4l7egnkoeC6UzU7JHW8NYQI0oPaV156w7fprsiaHsLtND3LGc8Sq8DTCk7KnlsMwO9SjJWrvhMagX2IpSzNZpgTbQ8CFFXrcaq8l298OIQtT1SmMEA6gBo2igHwQiXRXUvDiN6Qpwh20TwG12ysN6efVK5pthlDaaVkiFiOz1J2ZNjdxhf047bSFlXPF/beGJ0OHo+eBW67GUWXZBUsmbghcgu6zASiWQJggV3UynuV4P9pFWTErcllguGvqbmhaet2t+pnk/ZR8c16dKHG/ER10ftQ=
  on:
    tags: true
    node_js: "8"
